support rails 7 for `bundle exec derailed exec mem`
was getting:

/Users/dorianmariefr/.rvm/gems/ruby-3.0.3/gems/derailed_benchmarks-2.1.1/lib/derailed_benchmarks/load_tasks.rb:48:in `block (2 levels) in <top (required)>': undefined method `migrate' for ActiveRecord::Migrator:Class (NoMethodError)