From travis:
```
docker_mtu
resolvconf
git.checkout

0.62s$ git clone --depth=50 --branch=schneems/ruby-23 https://github.com/schneems/derailed_benchmarks.git schneems/derailed_benchmarks

0.01s
rvm

18.85s$ rvm use 2.2.0 --install --binary --fuzzy

Using gemfiles/rails_5_1.gemfile

$ export BUNDLE_GEMFILE=$PWD/gemfiles/rails_5_1.gemfile
ruby.versions

$ ruby --version

0.51s$ gem install bundler

Fetching bundler-2.1.4.gem

ERROR:  Error installing bundler:

	The last version of bundler (>= 0) to support your Ruby & RubyGems was 1.17.3. Try installing it with `gem install bundler -v 1.17.3`

	bundler requires Ruby version >= 2.3.0. The current ruby version is 2.2.0.0.

The command "gem install bundler" failed and exited with 1 during .

Your build has been stopped.
```